import Foundation

/// Produces export data (CSV, PDF) from inventory data. No UI; call from ViewModels or Views.
enum ExportService {

    // MARK: - CSV

    /// Full list of all items, sorted by category (order/name) then item name. Header row + one row per item. CSV-escaped.
    static func makeCSVData(
        items: [Item],
        categories: [Category],
        locations: [Location]
    ) -> Data {
        let sorted = sortItemsByCategoryThenName(items: items, categories: categories)
        let header = [
            "name", "description", "categoryName", "price", "priceCurrency", "purchaseDate", "quantity", "locationName"
        ]
        var rows: [[String]] = [header]
        for item in sorted {
            let catName = categories.first(where: { $0.id == item.categoryId })?.name ?? ""
            let locName = locations.first(where: { $0.id == item.locationId })?.name ?? ""
            rows.append([
                item.name,
                item.description,
                catName,
                item.price,
                item.priceCurrency,
                item.purchaseDate,
                String(item.quantity),
                locName
            ])
        }
        let csv = rows.map { row in
            row.map { escapeCSVField($0) }.joined(separator: ",")
        }.joined(separator: "\n")
        return Data(csv.utf8)
    }

    private static func escapeCSVField(_ field: String) -> String {
        let needsQuotes = field.contains(",") || field.contains("\n") || field.contains("\"")
        if !needsQuotes { return field }
        return "\"" + field.replacingOccurrences(of: "\"", with: "\"\"") + "\""
    }

    // MARK: - PDF

    /// One page per item, sorted by category then name. Uses SwiftUI ImageRenderer for correct layout (no overlapping text or cut-off images). Async due to thumbnail fetch.
    static func makePDFData(
        items: [Item],
        categories: [Category],
        locations: [Location],
        drive: DriveService
    ) async -> Data {
        let sorted = sortItemsByCategoryThenName(items: items, categories: categories)
        var thumbnailCache: [String: Data] = [:]
        for item in sorted {
            guard let fileId = item.photoIds.first else { continue }
            if thumbnailCache[fileId] != nil { continue }
            if let data = try? await drive.fetchImageData(fileId: fileId) {
                thumbnailCache[fileId] = data
            }
        }
        return await MainActor.run {
            PDFExportBuilder.buildPDF(
                items: sorted,
                categories: categories,
                thumbnailCache: thumbnailCache
            )
        }
    }

    // MARK: - ZIP (PDF + attachments)

    /// Builds a ZIP archive containing:
    /// - `pdf/mystuff_items.pdf` – the same PDF generated by `makePDFData`
    /// - `attachments/...` – all item photos and attachments (documents) grouped by item
    ///
    /// The returned URL points to a temporary file in `FileManager.default.temporaryDirectory`.
    static func makeZIPArchiveURL(
        items: [Item],
        categories: [Category],
        locations: [Location],
        attachments: [ItemAttachment],
        drive: DriveService
    ) async throws -> URL {
        // 1. Generate the PDF once using the existing pipeline.
        let pdfData = await makePDFData(
            items: items,
            categories: categories,
            locations: locations,
            drive: drive
        )

        let fileManager = FileManager.default
        let tempDir = fileManager.temporaryDirectory
            .appendingPathComponent("mystuff_zip_export_\(UUID().uuidString)", isDirectory: true)

        try fileManager.createDirectory(at: tempDir, withIntermediateDirectories: true)

        // Create Items root folder (one folder per item will live here).
        let itemsRootFolder = tempDir.appendingPathComponent("Items", isDirectory: true)
        try fileManager.createDirectory(at: itemsRootFolder, withIntermediateDirectories: true)

        // 2. Write PDF into root of archive
        let pdfURL = tempDir.appendingPathComponent("Items.pdf")
        try pdfData.write(to: pdfURL)

        // 3. Collect all asset download tasks (photos + attachments),
        //    and keep track of all file URLs we intend to include.
        struct PendingAsset {
            let fileId: String
            let isPhoto: Bool
            /// Base URL without extension; the final destination adds a guessed extension.
            let baseURL: URL
            let attachmentKind: ItemAttachment.Kind?
        }

        var pending: [PendingAsset] = []
        var fileURLs: [URL] = [pdfURL]

        // For attachment docs, we want per-item folders under Docs/.
        let itemsById: [String: Item] = Dictionary(uniqueKeysWithValues: items.map { ($0.id, $0) })

        // For each item: ensure its folder exists and add a one-page PDF (same layout as main export).
        // The per-item PDF file name matches the item folder name.
        // Then store item photos inside that item's folder under Items/.
        for item in items {
            let itemFolderName = sanitizedComponent(item.name.isEmpty ? "item_\(item.id)" : item.name)
            let itemFolder = itemsRootFolder.appendingPathComponent(itemFolderName, isDirectory: true)
            try? fileManager.createDirectory(at: itemFolder, withIntermediateDirectories: true)

            // Per-item one-page PDF using the same layout as the main export.
            do {
                var thumbCache: [String: Data] = [:]
                if let firstPhotoId = item.photoIds.first,
                   let imgData = try? await drive.fetchImageData(fileId: firstPhotoId) {
                    thumbCache[firstPhotoId] = imgData
                }
                let singlePDF = await MainActor.run {
                    PDFExportBuilder.buildPDF(
                        items: [item],
                        categories: categories,
                        thumbnailCache: thumbCache
                    )
                }
                let itemPDFURL = itemFolder.appendingPathComponent("\(itemFolderName).pdf")
                try singlePDF.write(to: itemPDFURL)
                fileURLs.append(itemPDFURL)
            } catch {
                // If per-item PDF generation fails, continue with the rest of the ZIP.
            }

            for (index, fileId) in item.photoIds.enumerated() {
                guard !fileId.isEmpty else { continue }
                let safeName = sanitizedComponent("\(item.name)_photo_\(index + 1)")
                let base = itemFolder.appendingPathComponent(safeName)
                pending.append(
                    PendingAsset(
                        fileId: fileId,
                        isPhoto: true,
                        baseURL: base,
                        attachmentKind: nil
                    )
                )
            }
        }

        // Item attachments (documents) from the Attachments sheet: grouped per item under Items/<item>/Docs.
        for attachment in attachments {
            guard !attachment.driveFileId.isEmpty else { continue }
            let itemName: String
            if let item = itemsById[attachment.itemId], !item.name.isEmpty {
                itemName = item.name
            } else {
                itemName = "item_\(attachment.itemId)"
            }
            let itemFolderName = sanitizedComponent(itemName)
            let itemFolder = itemsRootFolder.appendingPathComponent(itemFolderName, isDirectory: true)
            let itemDocsFolder = itemFolder.appendingPathComponent("Docs", isDirectory: true)
            try? fileManager.createDirectory(at: itemFolder, withIntermediateDirectories: true)
            try? fileManager.createDirectory(at: itemDocsFolder, withIntermediateDirectories: true)

            // Base filename is derived from the document kind (e.g. "Invoice", "UserManual", "Document").
            let baseName: String
            switch attachment.kind {
            case .invoice:
                baseName = "Invoice"
            case .userManual:
                baseName = "UserManual"
            case .other:
                baseName = "Document"
            }
            let safeName = sanitizedComponent(baseName)
            let base = itemDocsFolder.appendingPathComponent(safeName)
            pending.append(
                PendingAsset(
                    fileId: attachment.driveFileId,
                    isPhoto: false,
                    baseURL: base,
                    attachmentKind: attachment.kind
                )
            )
        }

        // 4. Download all assets (best-effort; failures are skipped).
        for asset in pending {
            do {
                let data: Data
                if asset.isPhoto {
                    data = try await drive.fetchImageData(fileId: asset.fileId)
                    let dest = asset.baseURL.appendingPathExtension("jpg")
                    try data.write(to: dest)
                    fileURLs.append(dest)
                } else {
                    data = try await drive.fetchFileData(fileId: asset.fileId)
                    let ext = guessedFileExtension(for: data)
                    let dest = asset.baseURL.appendingPathExtension(ext)
                    try data.write(to: dest)
                    fileURLs.append(dest)
                }
            } catch {
                // Ignore individual failures; ZIP will still be created with remaining files.
                continue
            }
        }

        // 5. Create a real ZIP archive from the prepared folder contents.
        let zipURL = fileManager.temporaryDirectory
            .appendingPathComponent("mystuff_items_\(UUID().uuidString)")
            .appendingPathExtension("zip")

        var writer = SimpleZipWriter()

        let basePath = tempDir.path.hasSuffix("/") ? tempDir.path : tempDir.path + "/"
        for url in fileURLs {
            let path = url.path
            guard path.hasPrefix(basePath) else { continue }
            guard fileManager.fileExists(atPath: path) else { continue }
            let relativePath = String(path.dropFirst(basePath.count))
            if let fileData = try? Data(contentsOf: url) {
                writer.addFile(named: relativePath, data: fileData)
            }
        }

        let zipData = writer.finalize()
        try zipData.write(to: zipURL)
        return zipURL
    }

    private static func sanitizedComponent(_ name: String) -> String {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_"))
        let fallback = trimmed.isEmpty ? "file" : trimmed
        return fallback
            .unicodeScalars
            .map { allowed.contains($0) ? String($0) : "_" }
            .joined()
    }

    private static func sortItemsByCategoryThenName(
        items: [Item],
        categories: [Category]
    ) -> [Item] {
        func orderKey(_ item: Item) -> (Int, String, String) {
            let cat = categories.first(where: { $0.id == item.categoryId })
            let order = cat?.order ?? Int.max
            let catName = cat?.name ?? ""
            return (order, catName, item.name)
        }
        return items.sorted { orderKey($0) < orderKey($1) }
    }

}

// MARK: - Minimal ZIP writer (store only, no compression)

private struct SimpleZipEntryMeta {
    let name: String
    let crc32: UInt32
    let compressedSize: UInt32
    let uncompressedSize: UInt32
    let localHeaderOffset: UInt32
}

private struct SimpleZipWriter {
    private var data = Data()
    private var entries: [SimpleZipEntryMeta] = []

    mutating func addFile(named name: String, data fileData: Data) {
        let nameData = Data(name.utf8)
        let offset = UInt32(data.count)
        let crc = crc32(fileData)
        let size = UInt32(truncatingIfNeeded: fileData.count)

        // Local file header
        data.appendUInt32LE(0x04034b50)       // signature
        data.appendUInt16LE(20)               // version needed to extract
        data.appendUInt16LE(0)                // general purpose bit flag
        data.appendUInt16LE(0)                // compression method (0 = store)
        data.appendUInt16LE(0)                // last mod file time
        data.appendUInt16LE(0)                // last mod file date
        data.appendUInt32LE(crc)              // CRC-32
        data.appendUInt32LE(size)             // compressed size
        data.appendUInt32LE(size)             // uncompressed size
        data.appendUInt16LE(UInt16(truncatingIfNeeded: nameData.count)) // file name length
        data.appendUInt16LE(0)                // extra field length
        data.append(nameData)                 // file name
        data.append(fileData)                 // file data

        let entry = SimpleZipEntryMeta(
            name: name,
            crc32: crc,
            compressedSize: size,
            uncompressedSize: size,
            localHeaderOffset: offset
        )
        entries.append(entry)
    }

    mutating func finalize() -> Data {
        let centralDirectoryStart = UInt32(data.count)

        for entry in entries {
            let nameData = Data(entry.name.utf8)

            // Central directory file header
            data.appendUInt32LE(0x02014b50)       // signature
            data.appendUInt16LE(20)               // version made by
            data.appendUInt16LE(20)               // version needed to extract
            data.appendUInt16LE(0)                // general purpose bit flag
            data.appendUInt16LE(0)                // compression method
            data.appendUInt16LE(0)                // last mod file time
            data.appendUInt16LE(0)                // last mod file date
            data.appendUInt32LE(entry.crc32)      // CRC-32
            data.appendUInt32LE(entry.compressedSize)   // compressed size
            data.appendUInt32LE(entry.uncompressedSize) // uncompressed size
            data.appendUInt16LE(UInt16(truncatingIfNeeded: nameData.count)) // file name length
            data.appendUInt16LE(0)                // extra field length
            data.appendUInt16LE(0)                // file comment length
            data.appendUInt16LE(0)                // disk number start
            data.appendUInt16LE(0)                // internal file attributes
            data.appendUInt32LE(0)                // external file attributes
            data.appendUInt32LE(entry.localHeaderOffset) // relative offset of local header
            data.append(nameData)                 // file name
        }

        let centralDirectoryEnd = UInt32(data.count)
        let centralDirectorySize = centralDirectoryEnd - centralDirectoryStart
        let entryCount = UInt16(truncatingIfNeeded: entries.count)

        // End of central directory record
        data.appendUInt32LE(0x06054b50)           // signature
        data.appendUInt16LE(0)                    // number of this disk
        data.appendUInt16LE(0)                    // disk where central directory starts
        data.appendUInt16LE(entryCount)           // number of central directory records on this disk
        data.appendUInt16LE(entryCount)           // total number of central directory records
        data.appendUInt32LE(centralDirectorySize) // size of central directory
        data.appendUInt32LE(centralDirectoryStart) // offset of start of central directory
        data.appendUInt16LE(0)                    // ZIP file comment length

        return data
    }
}

private func crc32(_ data: Data) -> UInt32 {
    var crc: UInt32 = 0xFFFF_FFFF
    for byte in data {
        crc ^= UInt32(byte)
        for _ in 0..<8 {
            let mask = UInt32(truncatingIfNeeded: Int32(crc & 1) * -1)
            crc = (crc >> 1) ^ (0xEDB88320 & mask)
        }
    }
    return crc ^ 0xFFFF_FFFF
}

private func guessedFileExtension(for data: Data) -> String {
    // PDF: "%PDF"
    if data.count >= 4 {
        let prefix = data.prefix(4)
        if prefix[ prefix.startIndex ] == 0x25, // %
           prefix[ prefix.index(prefix.startIndex, offsetBy: 1) ] == 0x50, // P
           prefix[ prefix.index(prefix.startIndex, offsetBy: 2) ] == 0x44, // D
           prefix[ prefix.index(prefix.startIndex, offsetBy: 3) ] == 0x46 { // F
            return "pdf"
        }
    }
    // JPEG: 0xFF 0xD8 0xFF
    if data.count >= 3 {
        let prefix = data.prefix(3)
        if prefix[ prefix.startIndex ] == 0xFF &&
           prefix[ prefix.index(prefix.startIndex, offsetBy: 1) ] == 0xD8 &&
           prefix[ prefix.index(prefix.startIndex, offsetBy: 2) ] == 0xFF {
            return "jpeg"
        }
    }
    // PNG: 0x89 'P' 'N' 'G'
    if data.count >= 4 {
        let prefix = data.prefix(4)
        if prefix[ prefix.startIndex ] == 0x89 &&
           prefix[ prefix.index(prefix.startIndex, offsetBy: 1) ] == 0x50 &&
           prefix[ prefix.index(prefix.startIndex, offsetBy: 2) ] == 0x4E &&
           prefix[ prefix.index(prefix.startIndex, offsetBy: 3) ] == 0x47 {
            return "png"
        }
    }
    // Fallback
    return "bin"
}

private extension Data {
    mutating func appendUInt16LE(_ value: UInt16) {
        var v = value.littleEndian
        Swift.withUnsafeBytes(of: &v) { buffer in
            self.append(contentsOf: buffer)
        }
    }

    mutating func appendUInt32LE(_ value: UInt32) {
        var v = value.littleEndian
        Swift.withUnsafeBytes(of: &v) { buffer in
            self.append(contentsOf: buffer)
        }
    }
}
